apiVersion: v1
data:
  run.sh: |
    echo "CLUSTERNAME: $CLUSTERNAME"
    CLUSTERRESPONSE=`curl -s "$RANCHERURL/v3/cluster" -H 'content-type: application/json' -H "Authorization: Bearer $APITOKEN" --data-binary '{"type":"cluster","name":"'$CLUSTERNAME'","import":true}'`
    echo "CLUSTERRESPONSE: $CLUSTERRESPONSE"
    CLUSTERID=`echo $CLUSTERRESPONSE | jq -r .id`
    echo "CLUSTERID: $CLUSTERID"
    ID=`curl -s "$RANCHERURL/v3/clusters/${CLUSTERID}/clusterregistrationtoken" -H 'content-type: application/json' -H "Authorization: Bearer $APITOKEN" --data-binary '{"type":"clusterRegistrationToken","clusterId":"'$CLUSTERID'"}'  |jq -r .id`
    echo "ID: $ID"
    AGENTURL=`curl -s "$RANCHERURL/v3/clusters/${CLUSTERID}/clusterregistrationtoken/$ID" -H 'content-type: application/json' -H "Authorization: Bearer $APITOKEN" | jq -r .manifestUrl`
    echo "AGENTURL: ${AGENTURL}"
    echo "apply to cluster..."
    kubectl wait pod/$CLUSTERNAME-vcluster-0 --for=condition=ready --timeout=300s
    kubectl exec $CLUSTERNAME-vcluster-0 -c vcluster -- kubectl apply -f "${AGENTURL}"
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
