apiVersion: v1
data:
  run.sh: |
    echo "CLUSTERNAME: $CLUSTERNAME"
    while [ -z "$CLUSTERRESPONSE" ]; do
      CLUSTERRESPONSE=`curl -s "$RANCHERURL/v3/cluster" -H 'content-type: application/json' -H "Authorization: Bearer $APITOKEN" --data-binary '{"type":"cluster","name":"'$CLUSTERNAME'","import":true}'`
      echo "CLUSTERRESPONSE: $CLUSTERRESPONSE"
    done
    CLUSTERID=`echo $CLUSTERRESPONSE | jq -r .id`
    echo "CLUSTERID: $CLUSTERID"
    while [ -n "$ID" ]; do
      ID=`curl -s "$RANCHERURL/v3/clusters/${CLUSTERID}/clusterregistrationtoken" -H 'content-type: application/json' -H "Authorization: Bearer $APITOKEN" --data-binary '{"type":"clusterRegistrationToken","clusterId":"'$CLUSTERID'"}'  |jq -r .id`
      echo "ID: $ID"
    done
    while [[ $AGENTURL = *clusters* ]]; do
      AGENTURL=`curl -s "$RANCHERURL/v3/clusters/${CLUSTERID}/clusterregistrationtoken/$ID" -H 'content-type: application/json' -H "Authorization: Bearer $APITOKEN" | jq -r .manifestUrl`
    done
      echo "AGENTURL: ${AGENTURL}"
      kubectl wait pod/$CLUSTERNAME-vcluster-0 --for=condition=ready --timeout=300s
      echo "apply to cluster..."
      kubectl exec $CLUSTERNAME-vcluster-0 -c vcluster -- kubectl apply -f "${AGENTURL}"
      sleep 4
      kubectl exec $CLUSTERNAME-vcluster-0 -c vcluster -- kubectl -n cattle-system set image deployment cattle-cluster-agent cluster-register=mtr.devops.telekom.de/rancher/rancher-agent:v2.7.5
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
