apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - image:  {{ .Values.image }}
        imagePullPolicy: Always
        name: register
        command: ["sh","-c"]
        args: ["/sidecar/run.sh"]
        volumeMounts:
        - mountPath: /sidecar
          name: {{ .Release.Name }}
        env:
        - name: APITOKEN
          value: {{ .Values.rancher.apitoken }}
        - name: RANCHERURL
          value: {{ .Values.rancher.url }}
        - name: CLUSTERNAME
          value: {{ .Values.clustername }}
      volumes:
      - configMap:
          defaultMode: 0755
          name: {{ .Release.Name }}
        name: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
